//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TattooProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArtistComment
    {
        public int Id { get; set; }
        public Nullable<int> ArtistId { get; set; }
        public Nullable<int> UserId { get; set; }
        public string Description { get; set; }
        public Nullable<int> ArtistWorkId { get; set; }
        public Nullable<System.DateTime> CDate { get; set; }
    }
}
