//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TattooProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artist
    {
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Username { get; set; }
        public string PasswordArtist { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Studios { get; set; }
        public string Comments { get; set; }
        public Nullable<float> Rates { get; set; }
        public string Gender { get; set; }
        public Nullable<int> Experience { get; set; }
        public string Description { get; set; }
        public string Expertise_Area { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public Nullable<int> AcceptedComment { get; set; }
        public Nullable<int> RejectedComment { get; set; }
        public Nullable<int> ViewCount { get; set; }
        public Nullable<int> ImageCount { get; set; }
        public int ArtistID { get; set; }
        public Nullable<decimal> TotalPoint { get; set; }
        public Nullable<int> TotalPointCount { get; set; }
    }
}
