//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TattooProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> bookingdate { get; set; }
        public Nullable<int> cuserid { get; set; }
        public Nullable<int> auserid { get; set; }
        public Nullable<System.TimeSpan> time { get; set; }
    }
}
