//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TattooProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TattooProjectEntities : DbContext
    {
        public TattooProjectEntities()
            : base("name=TattooProjectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Artist> Artists { get; set; }
        public virtual DbSet<ArtistComment> ArtistComments { get; set; }
        public virtual DbSet<ArtistWork> ArtistWorks { get; set; }
        public virtual DbSet<Booking> Bookings { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<vwBooking> vwBookings { get; set; }
        public virtual DbSet<UserArtistPoint> UserArtistPoints { get; set; }
    }
}
