$(function () {
    $(document).scroll(function () {
        var $nav = $("#mainNavbar");
        $nav.toggleClass("scrolled", $(this).scrollTop() > $nav.height());
    });
});


$(".dropdown li a ").click(function () {
    $(this).parents(".dropdown").find('.btn').html($(this).text());
    $(this).parents(".dropdown").find('.btn').val($(this).data('value'));
});


const data = [
    {
        "name": "Plato Sykes",
        "gender": "Male",
        "location": "Johnstone",
        "studio": "Magna LLP",
        "registrationDate": "2008/30/11",
        "rating": 5,
        "viewCount": 807,
        "modelCount": 81,
        "refusedCommentCount": 7,
        "acceptedCommentCount": 58,
        "description": "est ac mattis semper, dui lectus rutrum urna, nec luctus felis purus ac tellus. Suspendisse sed dolor. Fusce mi lorem, vehicula et, rutrum eu, ultrices sit amet, risus. Donec nibh enim, gravida sit amet, dapibus id, blandit at, nisi. Cum sociis natoque penatibus et magnis dis parturient montes,",
        "imgLink": "https://i.pinimg.com/originals/11/fb/c1/11fbc17dde7df5702b71a5c1c626fcc8.jpg",
        "experience": 8
    },
    {
        "name": "Ignacia Pope",
        "gender": "Female",
        "location": "Colleretto Castelnuovo",
        "studio": "Parturient Montes Incorporated",
        "registrationDate": "2018/26/03",
        "rating": 3,
        "viewCount": 698,
        "modelCount": 166,
        "refusedCommentCount": 8,
        "acceptedCommentCount": 74,
        "description": "diam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce aliquet magna a neque. Nullam ut nisi a odio semper cursus. Integer mollis. Integer tincidunt aliquam arcu. Aliquam ultrices iaculis odio. Nam interdum",
        "imgLink": "https://images.pexels.com/photos/3657575/pexels-photo-3657575.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
        "experience": 4
    },
    {
        "name": "Clare Bridges",
        "gender": "Male",
        "location": "Akron",
        "studio": "Aliquet Odio Industries",
        "registrationDate": "2015/09/09",
        "rating": 5,
        "viewCount": 15,
        "modelCount": 111,
        "refusedCommentCount": 1,
        "acceptedCommentCount": 52,
        "description": "Vivamus rhoncus. Donec est. Nunc ullamcorper, velit in aliquet lobortis, nisi nibh lacinia orci, consectetuer euismod est arcu ac orci. Ut semper pretium neque. Morbi quis urna. Nunc quis arcu vel quam dignissim pharetra. Nam ac nulla. In tincidunt congue",
        "imgLink": "https://images.pexels.com/photos/3657575/pexels-photo-3657575.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
        "experience": 2
    },
    {
        "name": "Hanae Wolf",
        "gender": "Female",
        "location": "Biez",
        "studio": "Tristique Inc.",
        "registrationDate": "2002/17/12",
        "rating": 4,
        "viewCount": 15,
        "modelCount": 67,
        "refusedCommentCount": 5,
        "acceptedCommentCount": 20,
        "description": "ipsum cursus vestibulum. Mauris magna. Duis dignissim tempor arcu. Vestibulum ut eros non enim commodo hendrerit. Donec porttitor tellus non magna. Nam ligula elit, pretium et, rutrum non, hendrerit id, ante. Nunc mauris sapien, cursus in, hendrerit consectetuer, cursus et, magna. Praesent interdum ligula eu enim. Etiam imperdiet dictum",
        "imgLink": "https://i.pinimg.com/originals/11/fb/c1/11fbc17dde7df5702b71a5c1c626fcc8.jpg",
        "experience": 5
    },
    {
        "name": "Quyn Floyd",
        "gender": "Female",
        "location": "Khanpur",
        "studio": "Malesuada Industries",
        "registrationDate": "2019/17/01",
        "rating": 5,
        "viewCount": 643,
        "modelCount": 95,
        "refusedCommentCount": 1,
        "acceptedCommentCount": 94,
        "description": "In faucibus. Morbi vehicula. Pellentesque tincidunt tempus risus. Donec egestas. Duis ac arcu. Nunc mauris. Morbi non sapien molestie orci tincidunt adipiscing. Mauris molestie pharetra nibh. Aliquam ornare, libero at",
        "imgLink": "https://images.pexels.com/photos/3657575/pexels-photo-3657575.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
        "experience": 3
    },
    {
        "name": "Amelia Mclaughlin",
        "gender": "Female",
        "location": "Labro",
        "studio": "Egestas Industries",
        "registrationDate": "2003/30/03",
        "rating": 1,
        "viewCount": 824,
        "modelCount": 62,
        "refusedCommentCount": 3,
        "acceptedCommentCount": 44,
        "description": "leo. Cras vehicula aliquet libero. Integer in magna. Phasellus dolor elit, pellentesque a, facilisis non, bibendum sed, est. Nunc laoreet lectus quis massa. Mauris vestibulum, neque sed dictum eleifend, nunc risus varius orci, in consequat enim diam vel arcu. Curabitur ut odio vel est tempor bibendum.",
        "imgLink": "https://i.pinimg.com/originals/11/fb/c1/11fbc17dde7df5702b71a5c1c626fcc8.jpg",
        "experience": 9
    },
    {
        "name": "Kermit Cherry",
        "gender": "Male",
        "location": "Quilpué",
        "studio": "Fringilla Euismod Enim Ltd",
        "registrationDate": "2021/17/08",
        "rating": 3,
        "viewCount": 755,
        "modelCount": 151,
        "refusedCommentCount": 9,
        "acceptedCommentCount": 39,
        "description": "fames ac turpis egestas. Aliquam fringilla cursus purus. Nullam scelerisque neque sed sem egestas blandit. Nam nulla magna, malesuada vel, convallis in, cursus et, eros. Proin ultrices. Duis volutpat nunc sit amet metus. Aliquam erat volutpat. Nulla facilisis. Suspendisse commodo tincidunt nibh. Phasellus nulla. Integer vulputate, risus a",
        "imgLink": "https://images.pexels.com/photos/3657575/pexels-photo-3657575.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
        "experience": 3
    },
    {
        "name": "Jessamine Collier",
        "gender": "Female",
        "location": "Erode",
        "studio": "Aliquam Arcu Aliquam Corp.",
        "registrationDate": "2010/29/08",
        "rating": 2,
        "viewCount": 253,
        "modelCount": 15,
        "refusedCommentCount": 10,
        "acceptedCommentCount": 91,
        "description": "enim. Nunc ut erat. Sed nunc est, mollis non, cursus non, egestas a, dui. Cras pellentesque. Sed dictum. Proin eget odio. Aliquam vulputate ullamcorper magna. Sed eu eros. Nam consequat dolor vitae dolor. Donec fringilla. Donec feugiat metus sit amet ante.",
        "imgLink": "https://i.pinimg.com/originals/11/fb/c1/11fbc17dde7df5702b71a5c1c626fcc8.jpg",
        "experience": 10
    },
    {
        "name": "Althea Carr",
        "gender": "Female",
        "location": "Minervino di Lecce",
        "studio": "Sit Amet Inc.",
        "registrationDate": "2001/08/10",
        "rating": 3,
        "viewCount": 810,
        "modelCount": 32,
        "refusedCommentCount": 7,
        "acceptedCommentCount": 4,
        "description": "non, lobortis quis, pede. Suspendisse dui. Fusce diam nunc, ullamcorper eu, euismod ac, fermentum vel, mauris. Integer sem elit, pharetra ut, pharetra sed, hendrerit a, arcu. Sed et libero. Proin mi. Aliquam gravida mauris ut mi. Duis risus odio, auctor vitae, aliquet nec, imperdiet nec, leo. Morbi neque tellus,",
        "imgLink": "https://images.pexels.com/photos/3657575/pexels-photo-3657575.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
        "experience": 1
    },
    {
        "name": "Uriel Donovan",
        "gender": "Female",
        "location": "Lehrte",
        "studio": "Fermentum Risus Corp.",
        "registrationDate": "2016/11/12",
        "rating": 1,
        "viewCount": 463,
        "modelCount": 47,
        "refusedCommentCount": 4,
        "acceptedCommentCount": 10,
        "description": "at risus. Nunc ac sem ut dolor dapibus gravida. Aliquam tincidunt, nunc ac mattis ornare, lectus ante dictum mi, ac mattis velit justo nec ante. Maecenas mi felis, adipiscing fringilla,",
        "imgLink": "https://images.pexels.com/photos/3657575/pexels-photo-3657575.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
        "experience": 4
    },
    {
        "name": "Hasad James",
        "gender": "Female",
        "location": "Sincelejo",
        "studio": "Porttitor Tellus PC",
        "registrationDate": "2018/17/06",
        "rating": 5,
        "viewCount": 358,
        "modelCount": 168,
        "refusedCommentCount": 8,
        "acceptedCommentCount": 1,
        "description": "orci sem eget massa. Suspendisse eleifend. Cras sed leo. Cras vehicula aliquet libero. Integer in magna. Phasellus dolor elit, pellentesque a, facilisis non, bibendum sed, est. Nunc laoreet lectus quis massa. Mauris vestibulum, neque sed dictum eleifend, nunc risus varius orci, in consequat enim diam vel arcu. Curabitur",
        "imgLink": "https://images.pexels.com/photos/3657575/pexels-photo-3657575.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
        "experience": 4
    },
    {
        "name": "Gil Hartman",
        "gender": "Male",
        "location": "Neuville",
        "studio": "Eget Associates",
        "registrationDate": "2011/10/12",
        "rating": 5,
        "viewCount": 167,
        "modelCount": 43,
        "refusedCommentCount": 3,
        "acceptedCommentCount": 93,
        "description": "Fusce dolor quam, elementum at, egestas a, scelerisque sed, sapien. Nunc pulvinar arcu et pede. Nunc sed orci lobortis augue scelerisque mollis. Phasellus libero mauris, aliquam eu, accumsan sed, facilisis vitae, orci.",
        "imgLink": "https://i.pinimg.com/originals/11/fb/c1/11fbc17dde7df5702b71a5c1c626fcc8.jpg",
        "experience": 9
    },
    {
        "name": "Alexis Shelton",
        "gender": "Female",
        "location": "Tijuana",
        "studio": "Malesuada Consulting",
        "registrationDate": "2001/19/09",
        "rating": 5,
        "viewCount": 439,
        "modelCount": 123,
        "refusedCommentCount": 7,
        "acceptedCommentCount": 28,
        "description": "consequat dolor vitae dolor. Donec fringilla. Donec feugiat metus sit amet ante. Vivamus non lorem vitae odio sagittis semper. Nam tempor diam dictum sapien. Aenean massa. Integer vitae nibh. Donec est mauris, rhoncus id, mollis nec, cursus a, enim. Suspendisse aliquet, sem ut",
        "imgLink": "https://i.pinimg.com/originals/11/fb/c1/11fbc17dde7df5702b71a5c1c626fcc8.jpg",
        "experience": 9
    },
    {
        "name": "Kevin Lynn",
        "gender": "Male",
        "location": "Río Bueno",
        "studio": "Ipsum Suspendisse Sagittis Institute",
        "registrationDate": "2013/09/06",
        "rating": 5,
        "viewCount": 45,
        "modelCount": 138,
        "refusedCommentCount": 4,
        "acceptedCommentCount": 99,
        "description": "ante dictum mi, ac mattis velit justo nec ante. Maecenas mi felis, adipiscing fringilla, porttitor vulputate, posuere vulputate, lacus. Cras interdum. Nunc sollicitudin commodo ipsum. Suspendisse non leo. Vivamus nibh dolor, nonummy ac, feugiat non, lobortis quis, pede. Suspendisse dui. Fusce diam nunc, ullamcorper eu, euismod",
        "imgLink": "https://i.pinimg.com/originals/11/fb/c1/11fbc17dde7df5702b71a5c1c626fcc8.jpg",
        "experience": 5
    },
    {
        "name": "Skyler Kinney",
        "gender": "Female",
        "location": "Santa Croce sull'Arno",
        "studio": "Enim Consequat Company",
        "registrationDate": "2008/18/11",
        "rating": 1,
        "viewCount": 965,
        "modelCount": 131,
        "refusedCommentCount": 10,
        "acceptedCommentCount": 13,
        "description": "Aliquam adipiscing lobortis risus. In mi pede, nonummy ut, molestie in, tempus eu, ligula. Aenean euismod mauris eu elit. Nulla facilisi. Sed neque. Sed eget lacus. Mauris non dui nec urna suscipit nonummy. Fusce fermentum fermentum arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;",
        "imgLink": "https://i.pinimg.com/originals/11/fb/c1/11fbc17dde7df5702b71a5c1c626fcc8.jpg",
        "experience": 3
    },
    {
        "name": "Madonna Daugherty",
        "gender": "Female",
        "location": "Jafarabad",
        "studio": "Consequat Auctor Nunc Industries",
        "registrationDate": "2005/26/10",
        "rating": 4,
        "viewCount": 838,
        "modelCount": 77,
        "refusedCommentCount": 10,
        "acceptedCommentCount": 11,
        "description": "ipsum cursus vestibulum. Mauris magna. Duis dignissim tempor arcu. Vestibulum ut eros non enim commodo hendrerit. Donec porttitor tellus non magna. Nam ligula elit, pretium et, rutrum non, hendrerit id, ante. Nunc mauris",
        "imgLink": "https://images.pexels.com/photos/3657575/pexels-photo-3657575.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
        "experience": 3
    },
    {
        "name": "Maggie Weeks",
        "gender": "Female",
        "location": "Isola del Gran Sasso d'Italia",
        "studio": "Mauris Limited",
        "registrationDate": "2008/07/09",
        "rating": 5,
        "viewCount": 272,
        "modelCount": 41,
        "refusedCommentCount": 7,
        "acceptedCommentCount": 72,
        "description": "interdum enim non nisi. Aenean eget metus. In nec orci. Donec nibh. Quisque nonummy ipsum non arcu. Vivamus sit amet risus. Donec egestas. Aliquam nec enim. Nunc ut erat. Sed nunc est, mollis non, cursus non, egestas a, dui. Cras pellentesque. Sed dictum. Proin eget",
        "imgLink": "https://images.pexels.com/photos/3657575/pexels-photo-3657575.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
        "experience": 9
    },
    {
        "name": "Yvonne Graves",
        "gender": "Female",
        "location": "Bingen",
        "studio": "Orci Lacus Vestibulum Limited",
        "registrationDate": "2014/06/03",
        "rating": 2,
        "viewCount": 792,
        "modelCount": 147,
        "refusedCommentCount": 3,
        "acceptedCommentCount": 29,
        "description": "ac nulla. In tincidunt congue turpis. In condimentum. Donec at arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec tincidunt. Donec vitae erat vel pede blandit congue. In scelerisque scelerisque dui. Suspendisse ac metus vitae velit egestas lacinia.",
        "imgLink": "https://i.pinimg.com/originals/11/fb/c1/11fbc17dde7df5702b71a5c1c626fcc8.jpg",
        "experience": 9
    },
    {
        "name": "Mariko Blevins",
        "gender": "Male",
        "location": "Penicuik",
        "studio": "Massa Quisque Porttitor Company",
        "registrationDate": "2007/05/11",
        "rating": 4,
        "viewCount": 469,
        "modelCount": 27,
        "refusedCommentCount": 5,
        "acceptedCommentCount": 84,
        "description": "aliquet vel, vulputate eu, odio. Phasellus at augue id ante dictum cursus. Nunc mauris elit, dictum eu, eleifend nec, malesuada ut, sem. Nulla interdum. Curabitur dictum. Phasellus in felis. Nulla tempor augue ac ipsum. Phasellus vitae mauris sit amet lorem semper auctor. Mauris vel turpis.",
        "imgLink": "https://images.pexels.com/photos/3657575/pexels-photo-3657575.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
        "experience": 7
    },
    {
        "name": "Urielle Stevenson",
        "gender": "Female",
        "location": "Ladispoli",
        "studio": "Vitae Dolor Associates",
        "registrationDate": "2019/15/06",
        "rating": 2,
        "viewCount": 694,
        "modelCount": 180,
        "refusedCommentCount": 2,
        "acceptedCommentCount": 34,
        "description": "tempus scelerisque, lorem ipsum sodales purus, in molestie tortor nibh sit amet orci. Ut sagittis lobortis mauris. Suspendisse aliquet molestie tellus. Aenean egestas hendrerit neque. In ornare sagittis felis. Donec tempor, est ac mattis semper, dui lectus rutrum urna,",
        "imgLink": "https://i.pinimg.com/originals/11/fb/c1/11fbc17dde7df5702b71a5c1c626fcc8.jpg",
        "experience": 7
    },
    {
        "name": "Shafira Skinner",
        "gender": "Female",
        "location": "Lithgow",
        "studio": "Magna Sed Eu Corp.",
        "registrationDate": "2001/05/08",
        "rating": 2,
        "viewCount": 538,
        "modelCount": 166,
        "refusedCommentCount": 6,
        "acceptedCommentCount": 97,
        "description": "orci luctus et ultrices posuere cubilia Curae; Phasellus ornare. Fusce mollis. Duis sit amet diam eu dolor egestas rhoncus. Proin nisl sem, consequat nec, mollis vitae, posuere at, velit. Cras lorem lorem, luctus",
        "imgLink": "https://i.pinimg.com/originals/11/fb/c1/11fbc17dde7df5702b71a5c1c626fcc8.jpg",
        "experience": 2
    },
    {
        "name": "Dai Owens",
        "gender": "Female",
        "location": "Fontanellato",
        "studio": "Neque Nullam PC",
        "registrationDate": "2002/17/09",
        "rating": 1,
        "viewCount": 869,
        "modelCount": 177,
        "refusedCommentCount": 9,
        "acceptedCommentCount": 1,
        "description": "amet, risus. Donec nibh enim, gravida sit amet, dapibus id, blandit at, nisi. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin vel nisl. Quisque fringilla euismod enim. Etiam gravida molestie arcu. Sed",
        "imgLink": "https://images.pexels.com/photos/3657575/pexels-photo-3657575.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
        "experience": 7
    },
    {
        "name": "Stone Mack",
        "gender": "Female",
        "location": "Kapuskasing",
        "studio": "Netus Inc.",
        "registrationDate": "2016/17/05",
        "rating": 2,
        "viewCount": 21,
        "modelCount": 191,
        "refusedCommentCount": 6,
        "acceptedCommentCount": 10,
        "description": "accumsan neque et nunc. Quisque ornare tortor at risus. Nunc ac sem ut dolor dapibus gravida. Aliquam tincidunt, nunc ac mattis ornare, lectus ante dictum mi, ac mattis velit justo",
        "imgLink": "https://i.pinimg.com/originals/11/fb/c1/11fbc17dde7df5702b71a5c1c626fcc8.jpg",
        "experience": 6
    },
    {
        "name": "Elton Ingram",
        "gender": "Female",
        "location": "West Vancouver",
        "studio": "Non Justo Proin Corp.",
        "registrationDate": "2020/11/11",
        "rating": 2,
        "viewCount": 369,
        "modelCount": 119,
        "refusedCommentCount": 9,
        "acceptedCommentCount": 20,
        "description": "tincidunt tempus risus. Donec egestas. Duis ac arcu. Nunc mauris. Morbi non sapien molestie orci tincidunt adipiscing. Mauris molestie pharetra nibh. Aliquam ornare, libero at auctor ullamcorper, nisl arcu iaculis enim, sit amet ornare lectus justo eu arcu.",
        "imgLink": "https://i.pinimg.com/originals/11/fb/c1/11fbc17dde7df5702b71a5c1c626fcc8.jpg",
        "experience": 2
    },
    {
        "name": "Georgia York",
        "gender": "Male",
        "location": "Saint-Prime",
        "studio": "Non Consulting",
        "registrationDate": "2012/12/02",
        "rating": 2,
        "viewCount": 47,
        "modelCount": 84,
        "refusedCommentCount": 10,
        "acceptedCommentCount": 17,
        "description": "gravida. Praesent eu nulla at sem molestie sodales. Mauris blandit enim consequat purus. Maecenas libero est, congue a, aliquet vel, vulputate eu, odio. Phasellus at augue id ante dictum cursus. Nunc mauris elit, dictum eu, eleifend nec, malesuada ut, sem. Nulla interdum. Curabitur dictum. Phasellus in",
        "imgLink": "https://images.pexels.com/photos/3657575/pexels-photo-3657575.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
        "experience": 4
    },
    {
        "name": "Mari Bowman",
        "gender": "Female",
        "location": "Val Rezzo",
        "studio": "Purus Industries",
        "registrationDate": "2001/27/08",
        "rating": 4,
        "viewCount": 539,
        "modelCount": 9,
        "refusedCommentCount": 3,
        "acceptedCommentCount": 56,
        "description": "vehicula risus. Nulla eget metus eu erat semper rutrum. Fusce dolor quam, elementum at, egestas a, scelerisque sed, sapien. Nunc pulvinar arcu et pede. Nunc sed orci lobortis augue scelerisque mollis. Phasellus libero mauris, aliquam eu, accumsan sed, facilisis",
        "imgLink": "https://i.pinimg.com/originals/11/fb/c1/11fbc17dde7df5702b71a5c1c626fcc8.jpg",
        "experience": 9
    },
    {
        "name": "Hermione Lloyd",
        "gender": "Female",
        "location": "San Nicolás",
        "studio": "Malesuada Integer Id LLP",
        "registrationDate": "2015/15/09",
        "rating": 1,
        "viewCount": 725,
        "modelCount": 153,
        "refusedCommentCount": 2,
        "acceptedCommentCount": 22,
        "description": "nibh. Donec est mauris, rhoncus id, mollis nec, cursus a, enim. Suspendisse aliquet, sem ut cursus luctus, ipsum leo elementum sem, vitae aliquam eros turpis non enim. Mauris quis turpis vitae purus",
        "imgLink": "https://i.pinimg.com/originals/11/fb/c1/11fbc17dde7df5702b71a5c1c626fcc8.jpg",
        "experience": 9
    },
    {
        "name": "Wesley Mack",
        "gender": "Female",
        "location": "Omaha",
        "studio": "Orci Adipiscing Non Corp.",
        "registrationDate": "2015/18/09",
        "rating": 4,
        "viewCount": 61,
        "modelCount": 25,
        "refusedCommentCount": 10,
        "acceptedCommentCount": 49,
        "description": "dui lectus rutrum urna, nec luctus felis purus ac tellus. Suspendisse sed dolor. Fusce mi lorem, vehicula et, rutrum eu, ultrices sit amet, risus. Donec nibh enim, gravida sit amet, dapibus id, blandit at, nisi. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin vel",
        "imgLink": "https://i.pinimg.com/originals/11/fb/c1/11fbc17dde7df5702b71a5c1c626fcc8.jpg",
        "experience": 4
    },
    {
        "name": "Herrod Petty",
        "gender": "Male",
        "location": "Helena",
        "studio": "Vivamus Non Lorem Associates",
        "registrationDate": "2002/18/08",
        "rating": 5,
        "viewCount": 363,
        "modelCount": 190,
        "refusedCommentCount": 1,
        "acceptedCommentCount": 55,
        "description": "eleifend egestas. Sed pharetra, felis eget varius ultrices, mauris ipsum porta elit, a feugiat tellus lorem eu metus. In lorem. Donec elementum, lorem ut aliquam iaculis, lacus pede sagittis augue, eu tempor erat neque non quam. Pellentesque habitant morbi tristique senectus et netus",
        "imgLink": "https://images.pexels.com/photos/3657575/pexels-photo-3657575.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
        "experience": 9
    },
    {
        "name": "Ulric Hewitt",
        "gender": "Male",
        "location": "Bordeaux",
        "studio": "Lacus Quisque Purus Inc.",
        "registrationDate": "2019/06/03",
        "rating": 5,
        "viewCount": 110,
        "modelCount": 137,
        "refusedCommentCount": 2,
        "acceptedCommentCount": 28,
        "description": "ridiculus mus. Donec dignissim magna a tortor. Nunc commodo auctor velit. Aliquam nisl. Nulla eu neque pellentesque massa lobortis ultrices. Vivamus rhoncus. Donec est. Nunc ullamcorper, velit in aliquet lobortis, nisi nibh lacinia orci, consectetuer euismod est arcu ac orci. Ut semper pretium neque. Morbi quis",
        "imgLink": "https://i.pinimg.com/originals/11/fb/c1/11fbc17dde7df5702b71a5c1c626fcc8.jpg",
        "experience": 4
    },
    {
        "name": "Yuli Carey",
        "gender": "Male",
        "location": "Bocchigliero",
        "studio": "Quisque Corp.",
        "registrationDate": "2003/01/02",
        "rating": 2,
        "viewCount": 304,
        "modelCount": 25,
        "refusedCommentCount": 1,
        "acceptedCommentCount": 64,
        "description": "vitae velit egestas lacinia. Sed congue, elit sed consequat auctor, nunc nulla vulputate dui, nec tempus mauris erat eget ipsum. Suspendisse sagittis. Nullam vitae diam. Proin dolor. Nulla semper tellus id nunc interdum feugiat. Sed nec metus facilisis lorem tristique aliquet. Phasellus fermentum convallis",
        "imgLink": "https://images.pexels.com/photos/3657575/pexels-photo-3657575.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
        "experience": 8
    },
    {
        "name": "Catherine Landry",
        "gender": "Female",
        "location": "Smolensk",
        "studio": "Est PC",
        "registrationDate": "2001/31/03",
        "rating": 4,
        "viewCount": 301,
        "modelCount": 4,
        "refusedCommentCount": 8,
        "acceptedCommentCount": 11,
        "description": "ac, feugiat non, lobortis quis, pede. Suspendisse dui. Fusce diam nunc, ullamcorper eu, euismod ac, fermentum vel, mauris. Integer sem elit, pharetra ut, pharetra sed, hendrerit a, arcu. Sed et libero. Proin mi. Aliquam gravida mauris ut mi. Duis risus odio,",
        "imgLink": "https://images.pexels.com/photos/3657575/pexels-photo-3657575.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
        "experience": 5
    },
    {
        "name": "Francis Sargent",
        "gender": "Female",
        "location": "Gore",
        "studio": "At Iaculis Inc.",
        "registrationDate": "2017/30/05",
        "rating": 3,
        "viewCount": 805,
        "modelCount": 125,
        "refusedCommentCount": 2,
        "acceptedCommentCount": 21,
        "description": "turpis egestas. Fusce aliquet magna a neque. Nullam ut nisi a odio semper cursus. Integer mollis. Integer tincidunt aliquam arcu. Aliquam ultrices iaculis odio. Nam interdum enim non nisi. Aenean",
        "imgLink": "https://i.pinimg.com/originals/11/fb/c1/11fbc17dde7df5702b71a5c1c626fcc8.jpg",
        "experience": 1
    },
    {
        "name": "Eaton Hodge",
        "gender": "Female",
        "location": "Stamford",
        "studio": "Nec Metus Facilisis Incorporated",
        "registrationDate": "2020/11/08",
        "rating": 4,
        "viewCount": 556,
        "modelCount": 155,
        "refusedCommentCount": 3,
        "acceptedCommentCount": 15,
        "description": "eu erat semper rutrum. Fusce dolor quam, elementum at, egestas a, scelerisque sed, sapien. Nunc pulvinar arcu et pede. Nunc sed orci lobortis augue scelerisque mollis. Phasellus libero mauris, aliquam eu, accumsan sed, facilisis vitae, orci. Phasellus dapibus quam quis diam. Pellentesque habitant morbi",
        "imgLink": "https://images.pexels.com/photos/3657575/pexels-photo-3657575.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
        "experience": 2
    },
    {
        "name": "Jeremy Mcfarland",
        "gender": "Male",
        "location": "Reading",
        "studio": "Vel Nisl Industries",
        "registrationDate": "2020/09/06",
        "rating": 4,
        "viewCount": 105,
        "modelCount": 162,
        "refusedCommentCount": 1,
        "acceptedCommentCount": 83,
        "description": "at, iaculis quis, pede. Praesent eu dui. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean eget magna. Suspendisse tristique neque venenatis lacus. Etiam bibendum fermentum metus. Aenean sed pede nec ante blandit viverra. Donec tempus, lorem fringilla ornare",
        "imgLink": "https://i.pinimg.com/originals/11/fb/c1/11fbc17dde7df5702b71a5c1c626fcc8.jpg",
        "experience": 4
    },
    {
        "name": "Angela Terrell",
        "gender": "Female",
        "location": "Amersfoort",
        "studio": "Ipsum Cursus Company",
        "registrationDate": "2009/25/02",
        "rating": 3,
        "viewCount": 311,
        "modelCount": 34,
        "refusedCommentCount": 9,
        "acceptedCommentCount": 45,
        "description": "ac urna. Ut tincidunt vehicula risus. Nulla eget metus eu erat semper rutrum. Fusce dolor quam, elementum at, egestas a, scelerisque sed, sapien. Nunc pulvinar arcu et pede. Nunc sed orci lobortis",
        "imgLink": "https://i.pinimg.com/originals/11/fb/c1/11fbc17dde7df5702b71a5c1c626fcc8.jpg",
        "experience": 2
    },
    {
        "name": "Madison Todd",
        "gender": "Female",
        "location": "Ryazan",
        "studio": "Dictum Eleifend Ltd",
        "registrationDate": "2015/20/01",
        "rating": 4,
        "viewCount": 915,
        "modelCount": 148,
        "refusedCommentCount": 8,
        "acceptedCommentCount": 62,
        "description": "molestie tortor nibh sit amet orci. Ut sagittis lobortis mauris. Suspendisse aliquet molestie tellus. Aenean egestas hendrerit neque. In ornare sagittis felis. Donec tempor, est ac mattis semper, dui lectus rutrum urna, nec luctus felis purus ac tellus. Suspendisse sed dolor. Fusce mi lorem, vehicula et, rutrum",
        "imgLink": "https://i.pinimg.com/originals/11/fb/c1/11fbc17dde7df5702b71a5c1c626fcc8.jpg",
        "experience": 4
    },
    {
        "name": "Fallon English",
        "gender": "Female",
        "location": "Vicuña",
        "studio": "Nec Imperdiet Consulting",
        "registrationDate": "2003/02/02",
        "rating": 4,
        "viewCount": 455,
        "modelCount": 73,
        "refusedCommentCount": 7,
        "acceptedCommentCount": 24,
        "description": "Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec urna et arcu imperdiet ullamcorper. Duis at lacus. Quisque purus sapien, gravida non, sollicitudin a, malesuada id, erat. Etiam vestibulum massa rutrum magna. Cras convallis convallis dolor. Quisque tincidunt pede ac",
        "imgLink": "https://images.pexels.com/photos/3657575/pexels-photo-3657575.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
        "experience": 2
    },
    {
        "name": "Nora Kline",
        "gender": "Male",
        "location": "Hertford",
        "studio": "Torquent Per Conubia Incorporated",
        "registrationDate": "2019/20/07",
        "rating": 2,
        "viewCount": 895,
        "modelCount": 66,
        "refusedCommentCount": 4,
        "acceptedCommentCount": 9,
        "description": "Quisque tincidunt pede ac urna. Ut tincidunt vehicula risus. Nulla eget metus eu erat semper rutrum. Fusce dolor quam, elementum at, egestas a, scelerisque sed, sapien. Nunc pulvinar arcu et pede. Nunc sed orci lobortis augue scelerisque",
        "imgLink": "https://images.pexels.com/photos/3657575/pexels-photo-3657575.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
        "experience": 1
    },
    {
        "name": "Rama Williamson",
        "gender": "Female",
        "location": "Hoshiarpur",
        "studio": "Et Magnis Dis Associates",
        "registrationDate": "2010/04/10",
        "rating": 1,
        "viewCount": 364,
        "modelCount": 4,
        "refusedCommentCount": 5,
        "acceptedCommentCount": 44,
        "description": "ipsum leo elementum sem, vitae aliquam eros turpis non enim. Mauris quis turpis vitae purus gravida sagittis. Duis gravida. Praesent eu nulla at sem molestie sodales. Mauris blandit enim consequat purus. Maecenas libero est, congue a, aliquet vel, vulputate eu, odio. Phasellus at augue id",
        "imgLink": "https://images.pexels.com/photos/3657575/pexels-photo-3657575.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
        "experience": 8
    },
    {
        "name": "Camilla Buchanan",
        "gender": "Male",
        "location": "Parrano",
        "studio": "Vitae Purus Gravida Inc.",
        "registrationDate": "2011/18/11",
        "rating": 4,
        "viewCount": 637,
        "modelCount": 125,
        "refusedCommentCount": 10,
        "acceptedCommentCount": 100,
        "description": "molestie tellus. Aenean egestas hendrerit neque. In ornare sagittis felis. Donec tempor, est ac mattis semper, dui lectus rutrum urna, nec luctus felis purus ac tellus. Suspendisse sed dolor. Fusce mi lorem, vehicula et, rutrum eu, ultrices sit amet, risus. Donec nibh enim, gravida",
        "imgLink": "https://i.pinimg.com/originals/11/fb/c1/11fbc17dde7df5702b71a5c1c626fcc8.jpg",
        "experience": 4
    },
    {
        "name": "Hunter Clements",
        "gender": "Male",
        "location": "Midlands",
        "studio": "Sem Magna Associates",
        "registrationDate": "2012/17/12",
        "rating": 3,
        "viewCount": 969,
        "modelCount": 57,
        "refusedCommentCount": 1,
        "acceptedCommentCount": 20,
        "description": "ut eros non enim commodo hendrerit. Donec porttitor tellus non magna. Nam ligula elit, pretium et, rutrum non, hendrerit id, ante. Nunc mauris sapien, cursus in, hendrerit consectetuer, cursus et, magna.",
        "imgLink": "https://i.pinimg.com/originals/11/fb/c1/11fbc17dde7df5702b71a5c1c626fcc8.jpg",
        "experience": 9
    },
    {
        "name": "Olga Chang",
        "gender": "Female",
        "location": "Spresiano",
        "studio": "Feugiat Sed Nec LLP",
        "registrationDate": "2019/20/09",
        "rating": 1,
        "viewCount": 178,
        "modelCount": 151,
        "refusedCommentCount": 4,
        "acceptedCommentCount": 31,
        "description": "Proin nisl sem, consequat nec, mollis vitae, posuere at, velit. Cras lorem lorem, luctus ut, pellentesque eget, dictum placerat, augue. Sed molestie. Sed id risus quis diam luctus lobortis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Mauris ut quam",
        "imgLink": "https://i.pinimg.com/originals/11/fb/c1/11fbc17dde7df5702b71a5c1c626fcc8.jpg",
        "experience": 3
    },
    {
        "name": "Heidi Anthony",
        "gender": "Male",
        "location": "Gimpo",
        "studio": "Est Corporation",
        "registrationDate": "2011/15/09",
        "rating": 3,
        "viewCount": 102,
        "modelCount": 170,
        "refusedCommentCount": 7,
        "acceptedCommentCount": 1,
        "description": "Nam porttitor scelerisque neque. Nullam nisl. Maecenas malesuada fringilla est. Mauris eu turpis. Nulla aliquet. Proin velit. Sed malesuada augue ut lacus. Nulla tincidunt, neque vitae semper egestas, urna justo faucibus lectus, a sollicitudin orci sem eget massa. Suspendisse eleifend. Cras sed leo. Cras vehicula",
        "imgLink": "https://images.pexels.com/photos/3657575/pexels-photo-3657575.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
        "experience": 1
    },
    {
        "name": "Erica Clemons",
        "gender": "Female",
        "location": "Rae-Edzo",
        "studio": "Rutrum LLC",
        "registrationDate": "2005/18/09",
        "rating": 2,
        "viewCount": 972,
        "modelCount": 81,
        "refusedCommentCount": 2,
        "acceptedCommentCount": 13,
        "description": "Fusce diam nunc, ullamcorper eu, euismod ac, fermentum vel, mauris. Integer sem elit, pharetra ut, pharetra sed, hendrerit a, arcu. Sed et libero. Proin mi. Aliquam gravida mauris ut mi. Duis risus odio, auctor vitae, aliquet nec, imperdiet",
        "imgLink": "https://i.pinimg.com/originals/11/fb/c1/11fbc17dde7df5702b71a5c1c626fcc8.jpg",
        "experience": 3
    },
    {
        "name": "Evan Fernandez",
        "gender": "Male",
        "location": "Mersin",
        "studio": "Hendrerit Industries",
        "registrationDate": "2001/07/04",
        "rating": 3,
        "viewCount": 695,
        "modelCount": 43,
        "refusedCommentCount": 8,
        "acceptedCommentCount": 50,
        "description": "a purus. Duis elementum, dui quis accumsan convallis, ante lectus convallis est, vitae sodales nisi magna sed dui. Fusce aliquam, enim nec tempus scelerisque, lorem ipsum sodales purus, in molestie tortor nibh sit amet orci. Ut sagittis lobortis mauris. Suspendisse aliquet molestie tellus. Aenean egestas",
        "imgLink": "https://i.pinimg.com/originals/11/fb/c1/11fbc17dde7df5702b71a5c1c626fcc8.jpg",
        "experience": 7
    },
    {
        "name": "Aquila Edwards",
        "gender": "Male",
        "location": "Carahue",
        "studio": "Ac Feugiat Associates",
        "registrationDate": "2018/19/05",
        "rating": 4,
        "viewCount": 851,
        "modelCount": 27,
        "refusedCommentCount": 2,
        "acceptedCommentCount": 98,
        "description": "tellus non magna. Nam ligula elit, pretium et, rutrum non, hendrerit id, ante. Nunc mauris sapien, cursus in, hendrerit consectetuer, cursus et, magna. Praesent interdum ligula eu enim. Etiam imperdiet dictum",
        "imgLink": "https://images.pexels.com/photos/3657575/pexels-photo-3657575.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
        "experience": 3
    },
    {
        "name": "Nathaniel Mcconnell",
        "gender": "Male",
        "location": "Baardegem",
        "studio": "Curae; Donec Tincidunt Associates",
        "registrationDate": "2009/17/10",
        "rating": 1,
        "viewCount": 533,
        "modelCount": 45,
        "refusedCommentCount": 5,
        "acceptedCommentCount": 3,
        "description": "vel arcu. Curabitur ut odio vel est tempor bibendum. Donec felis orci, adipiscing non, luctus sit amet, faucibus ut, nulla. Cras eu tellus eu augue porttitor interdum. Sed auctor odio a purus. Duis elementum, dui quis accumsan convallis, ante lectus convallis est, vitae sodales",
        "imgLink": "https://images.pexels.com/photos/3657575/pexels-photo-3657575.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
        "experience": 1
    },
    {
        "name": "Rinah Atkins",
        "gender": "Female",
        "location": "Quinta de Tilcoco",
        "studio": "Libero Est Congue LLP",
        "registrationDate": "2005/19/12",
        "rating": 4,
        "viewCount": 656,
        "modelCount": 142,
        "refusedCommentCount": 10,
        "acceptedCommentCount": 69,
        "description": "cursus. Nunc mauris elit, dictum eu, eleifend nec, malesuada ut, sem. Nulla interdum. Curabitur dictum. Phasellus in felis. Nulla tempor augue ac ipsum. Phasellus vitae mauris sit amet lorem semper auctor. Mauris vel turpis. Aliquam adipiscing lobortis risus. In mi pede, nonummy ut, molestie in, tempus",
        "imgLink": "https://i.pinimg.com/originals/11/fb/c1/11fbc17dde7df5702b71a5c1c626fcc8.jpg",
        "experience": 1
    },
    {
        "name": "Rina Woods",
        "gender": "Male",
        "location": "Trier",
        "studio": "Erat In Institute",
        "registrationDate": "2005/03/04",
        "rating": 3,
        "viewCount": 612,
        "modelCount": 159,
        "refusedCommentCount": 6,
        "acceptedCommentCount": 85,
        "description": "congue a, aliquet vel, vulputate eu, odio. Phasellus at augue id ante dictum cursus. Nunc mauris elit, dictum eu, eleifend nec, malesuada ut, sem. Nulla interdum. Curabitur dictum. Phasellus in felis. Nulla tempor augue ac ipsum. Phasellus vitae mauris sit amet lorem semper auctor. Mauris",
        "imgLink": "https://images.pexels.com/photos/3657575/pexels-photo-3657575.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
        "experience": 1
    },
    {
        "name": "Sheila Acevedo",
        "gender": "Male",
        "location": "Baracaldo",
        "studio": "Nulla Institute",
        "registrationDate": "2021/07/01",
        "rating": 4,
        "viewCount": 710,
        "modelCount": 144,
        "refusedCommentCount": 6,
        "acceptedCommentCount": 57,
        "description": "Aliquam adipiscing lobortis risus. In mi pede, nonummy ut, molestie in, tempus eu, ligula. Aenean euismod mauris eu elit. Nulla facilisi. Sed neque. Sed eget lacus. Mauris non dui nec urna suscipit nonummy. Fusce fermentum fermentum arcu. Vestibulum ante ipsum primis in faucibus orci",
        "imgLink": "https://images.pexels.com/photos/3657575/pexels-photo-3657575.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
        "experience": 9
    },
    {
        "name": "Gabriel Peterson",
        "gender": "Female",
        "location": "Rawalpindi",
        "studio": "Sed Eget Corp.",
        "registrationDate": "2003/02/08",
        "rating": 2,
        "viewCount": 545,
        "modelCount": 75,
        "refusedCommentCount": 1,
        "acceptedCommentCount": 53,
        "description": "enim, sit amet ornare lectus justo eu arcu. Morbi sit amet massa. Quisque porttitor eros nec tellus. Nunc lectus pede, ultrices a, auctor non, feugiat nec, diam. Duis mi enim, condimentum eget, volutpat ornare, facilisis eget, ipsum.",
        "imgLink": "https://images.pexels.com/photos/3657575/pexels-photo-3657575.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
        "experience": 3
    },
    {
        "name": "Sophia Bright",
        "gender": "Male",
        "location": "Torre Cajetani",
        "studio": "Vel Limited",
        "registrationDate": "2016/01/10",
        "rating": 2,
        "viewCount": 237,
        "modelCount": 136,
        "refusedCommentCount": 4,
        "acceptedCommentCount": 10,
        "description": "Praesent luctus. Curabitur egestas nunc sed libero. Proin sed turpis nec mauris blandit mattis. Cras eget nisi dictum augue malesuada malesuada. Integer id magna et ipsum cursus vestibulum. Mauris magna. Duis dignissim tempor arcu. Vestibulum ut eros non enim commodo",
        "imgLink": "https://images.pexels.com/photos/3657575/pexels-photo-3657575.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
        "experience": 10
    },
    {
        "name": "Charity Mccarty",
        "gender": "Male",
        "location": "Ipswich",
        "studio": "Erat Etiam Vestibulum Foundation",
        "registrationDate": "2002/27/12",
        "rating": 5,
        "viewCount": 400,
        "modelCount": 164,
        "refusedCommentCount": 3,
        "acceptedCommentCount": 43,
        "description": "natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean eget magna. Suspendisse tristique neque venenatis lacus. Etiam bibendum fermentum metus. Aenean sed pede nec ante blandit viverra. Donec tempus, lorem fringilla ornare placerat,",
        "imgLink": "https://i.pinimg.com/originals/11/fb/c1/11fbc17dde7df5702b71a5c1c626fcc8.jpg",
        "experience": 6
    },
    {
        "name": "Sylvia Hamilton",
        "gender": "Female",
        "location": "Crystal Springs",
        "studio": "Felis Corp.",
        "registrationDate": "2006/07/09",
        "rating": 2,
        "viewCount": 153,
        "modelCount": 78,
        "refusedCommentCount": 6,
        "acceptedCommentCount": 22,
        "description": "venenatis vel, faucibus id, libero. Donec consectetuer mauris id sapien. Cras dolor dolor, tempus non, lacinia at, iaculis quis, pede. Praesent eu dui. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean eget magna. Suspendisse tristique neque venenatis",
        "imgLink": "https://i.pinimg.com/originals/11/fb/c1/11fbc17dde7df5702b71a5c1c626fcc8.jpg",
        "experience": 10
    },
    {
        "name": "Mikayla Colon",
        "gender": "Female",
        "location": "Sète",
        "studio": "Vivamus Non Incorporated",
        "registrationDate": "2005/18/08",
        "rating": 4,
        "viewCount": 481,
        "modelCount": 154,
        "refusedCommentCount": 5,
        "acceptedCommentCount": 57,
        "description": "id ante dictum cursus. Nunc mauris elit, dictum eu, eleifend nec, malesuada ut, sem. Nulla interdum. Curabitur dictum. Phasellus in felis. Nulla tempor augue ac ipsum. Phasellus vitae mauris sit amet lorem semper",
        "imgLink": "https://i.pinimg.com/originals/11/fb/c1/11fbc17dde7df5702b71a5c1c626fcc8.jpg",
        "experience": 10
    },
    {
        "name": "Aladdin Cantrell",
        "gender": "Female",
        "location": "Birkenhead",
        "studio": "Consectetuer Limited",
        "registrationDate": "2015/23/05",
        "rating": 2,
        "viewCount": 708,
        "modelCount": 80,
        "refusedCommentCount": 3,
        "acceptedCommentCount": 88,
        "description": "rutrum. Fusce dolor quam, elementum at, egestas a, scelerisque sed, sapien. Nunc pulvinar arcu et pede. Nunc sed orci lobortis augue scelerisque mollis. Phasellus libero mauris, aliquam eu, accumsan sed, facilisis vitae, orci. Phasellus dapibus quam quis diam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac",
        "imgLink": "https://images.pexels.com/photos/3657575/pexels-photo-3657575.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
        "experience": 6
    },
    {
        "name": "Rachel Buchanan",
        "gender": "Female",
        "location": "Gulfport",
        "studio": "Metus Eu Erat Incorporated",
        "registrationDate": "2005/24/06",
        "rating": 4,
        "viewCount": 935,
        "modelCount": 28,
        "refusedCommentCount": 3,
        "acceptedCommentCount": 59,
        "description": "egestas, urna justo faucibus lectus, a sollicitudin orci sem eget massa. Suspendisse eleifend. Cras sed leo. Cras vehicula aliquet libero. Integer in magna. Phasellus dolor elit, pellentesque a, facilisis non, bibendum sed, est. Nunc laoreet lectus quis massa.",
        "imgLink": "https://images.pexels.com/photos/3657575/pexels-photo-3657575.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
        "experience": 1
    },
    {
        "name": "David Perkins",
        "gender": "Female",
        "location": "Fort Simpson",
        "studio": "Pede Cum Sociis LLP",
        "registrationDate": "2008/02/07",
        "rating": 4,
        "viewCount": 293,
        "modelCount": 108,
        "refusedCommentCount": 2,
        "acceptedCommentCount": 60,
        "description": "mus. Aenean eget magna. Suspendisse tristique neque venenatis lacus. Etiam bibendum fermentum metus. Aenean sed pede nec ante blandit viverra. Donec tempus, lorem fringilla ornare placerat, orci lacus vestibulum lorem, sit amet ultricies sem magna nec quam. Curabitur vel",
        "imgLink": "https://i.pinimg.com/originals/11/fb/c1/11fbc17dde7df5702b71a5c1c626fcc8.jpg",
        "experience": 2
    },
    {
        "name": "Holmes Rivas",
        "gender": "Male",
        "location": "Neustadt",
        "studio": "Ut Pharetra Sed Associates",
        "registrationDate": "2004/11/05",
        "rating": 3,
        "viewCount": 634,
        "modelCount": 7,
        "refusedCommentCount": 6,
        "acceptedCommentCount": 77,
        "description": "Nunc commodo auctor velit. Aliquam nisl. Nulla eu neque pellentesque massa lobortis ultrices. Vivamus rhoncus. Donec est. Nunc ullamcorper, velit in aliquet lobortis, nisi nibh lacinia orci, consectetuer euismod est arcu ac",
        "imgLink": "https://i.pinimg.com/originals/11/fb/c1/11fbc17dde7df5702b71a5c1c626fcc8.jpg",
        "experience": 3
    },
    {
        "name": "Germaine Atkins",
        "gender": "Male",
        "location": "Probolinggo",
        "studio": "Quisque PC",
        "registrationDate": "2012/24/09",
        "rating": 2,
        "viewCount": 986,
        "modelCount": 126,
        "refusedCommentCount": 3,
        "acceptedCommentCount": 15,
        "description": "est. Nunc ullamcorper, velit in aliquet lobortis, nisi nibh lacinia orci, consectetuer euismod est arcu ac orci. Ut semper pretium neque. Morbi quis urna. Nunc quis arcu vel quam dignissim pharetra. Nam ac nulla. In tincidunt congue turpis. In condimentum. Donec at arcu. Vestibulum",
        "imgLink": "https://i.pinimg.com/originals/11/fb/c1/11fbc17dde7df5702b71a5c1c626fcc8.jpg",
        "experience": 10
    },
    {
        "name": "Minerva Bean",
        "gender": "Male",
        "location": "Merksem",
        "studio": "Lectus Justo Ltd",
        "registrationDate": "2011/12/09",
        "rating": 5,
        "viewCount": 132,
        "modelCount": 21,
        "refusedCommentCount": 3,
        "acceptedCommentCount": 86,
        "description": "natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean eget magna. Suspendisse tristique neque venenatis lacus. Etiam bibendum fermentum metus. Aenean sed pede nec ante blandit viverra. Donec tempus, lorem fringilla ornare placerat, orci lacus vestibulum lorem, sit amet ultricies sem magna nec quam. Curabitur vel",
        "imgLink": "https://i.pinimg.com/originals/11/fb/c1/11fbc17dde7df5702b71a5c1c626fcc8.jpg",
        "experience": 9
    },
    {
        "name": "Pamela Kirby",
        "gender": "Male",
        "location": "Kempten",
        "studio": "Ipsum Ac PC",
        "registrationDate": "2008/20/08",
        "rating": 3,
        "viewCount": 359,
        "modelCount": 76,
        "refusedCommentCount": 9,
        "acceptedCommentCount": 16,
        "description": "libero at auctor ullamcorper, nisl arcu iaculis enim, sit amet ornare lectus justo eu arcu. Morbi sit amet massa. Quisque porttitor eros nec tellus. Nunc lectus pede, ultrices a, auctor non, feugiat nec, diam. Duis",
        "imgLink": "https://images.pexels.com/photos/3657575/pexels-photo-3657575.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
        "experience": 10
    },
    {
        "name": "Neve Wilcox",
        "gender": "Male",
        "location": "Knokke",
        "studio": "Ac Ipsum Corporation",
        "registrationDate": "2016/22/03",
        "rating": 1,
        "viewCount": 491,
        "modelCount": 169,
        "refusedCommentCount": 2,
        "acceptedCommentCount": 6,
        "description": "Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin vel arcu eu odio tristique pharetra. Quisque ac libero nec ligula consectetuer rhoncus. Nullam velit dui, semper et, lacinia vitae, sodales at, velit. Pellentesque ultricies dignissim",
        "imgLink": "https://images.pexels.com/photos/3657575/pexels-photo-3657575.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
        "experience": 4
    },
    {
        "name": "Zorita Perez",
        "gender": "Female",
        "location": "Porvenir",
        "studio": "Malesuada Consulting",
        "registrationDate": "2005/19/07",
        "rating": 3,
        "viewCount": 417,
        "modelCount": 153,
        "refusedCommentCount": 10,
        "acceptedCommentCount": 81,
        "description": "purus mauris a nunc. In at pede. Cras vulputate velit eu sem. Pellentesque ut ipsum ac mi eleifend egestas. Sed pharetra, felis eget varius ultrices, mauris ipsum porta elit, a feugiat tellus lorem eu metus. In lorem. Donec elementum, lorem ut aliquam iaculis, lacus pede sagittis augue, eu",
        "imgLink": "https://images.pexels.com/photos/3657575/pexels-photo-3657575.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
        "experience": 5
    },
    {
        "name": "Tana Greene",
        "gender": "Male",
        "location": "Maintal",
        "studio": "Interdum Consulting",
        "registrationDate": "2007/05/06",
        "rating": 4,
        "viewCount": 857,
        "modelCount": 166,
        "refusedCommentCount": 2,
        "acceptedCommentCount": 28,
        "description": "sollicitudin commodo ipsum. Suspendisse non leo. Vivamus nibh dolor, nonummy ac, feugiat non, lobortis quis, pede. Suspendisse dui. Fusce diam nunc, ullamcorper eu, euismod ac, fermentum vel, mauris. Integer sem elit, pharetra ut, pharetra sed, hendrerit a, arcu. Sed et",
        "imgLink": "https://i.pinimg.com/originals/11/fb/c1/11fbc17dde7df5702b71a5c1c626fcc8.jpg",
        "experience": 10
    },
    {
        "name": "Cynthia Adams",
        "gender": "Male",
        "location": "Poucet",
        "studio": "Mauris Limited",
        "registrationDate": "2001/20/10",
        "rating": 2,
        "viewCount": 970,
        "modelCount": 165,
        "refusedCommentCount": 2,
        "acceptedCommentCount": 92,
        "description": "nunc, ullamcorper eu, euismod ac, fermentum vel, mauris. Integer sem elit, pharetra ut, pharetra sed, hendrerit a, arcu. Sed et libero. Proin mi. Aliquam gravida mauris ut mi. Duis risus odio, auctor vitae, aliquet nec, imperdiet nec, leo. Morbi neque tellus, imperdiet",
        "imgLink": "https://i.pinimg.com/originals/11/fb/c1/11fbc17dde7df5702b71a5c1c626fcc8.jpg",
        "experience": 3
    },
    {
        "name": "Randall Herrera",
        "gender": "Female",
        "location": "Domodedovo",
        "studio": "Mauris Rhoncus Id Corp.",
        "registrationDate": "2012/25/05",
        "rating": 1,
        "viewCount": 988,
        "modelCount": 170,
        "refusedCommentCount": 9,
        "acceptedCommentCount": 15,
        "description": "ipsum dolor sit amet, consectetuer adipiscing elit. Etiam laoreet, libero et tristique pellentesque, tellus sem mollis dui, in sodales elit erat vitae risus. Duis a mi fringilla mi lacinia mattis. Integer eu lacus. Quisque imperdiet, erat nonummy",
        "imgLink": "https://images.pexels.com/photos/3657575/pexels-photo-3657575.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
        "experience": 3
    },
    {
        "name": "Noble Cooke",
        "gender": "Female",
        "location": "Getafe",
        "studio": "Nibh Sit Amet Incorporated",
        "registrationDate": "2001/03/05",
        "rating": 4,
        "viewCount": 456,
        "modelCount": 119,
        "refusedCommentCount": 10,
        "acceptedCommentCount": 95,
        "description": "ornare. Fusce mollis. Duis sit amet diam eu dolor egestas rhoncus. Proin nisl sem, consequat nec, mollis vitae, posuere at, velit. Cras lorem lorem, luctus ut, pellentesque eget, dictum placerat, augue. Sed molestie. Sed id risus quis diam luctus lobortis. Class aptent taciti sociosqu ad litora torquent per",
        "imgLink": "https://images.pexels.com/photos/3657575/pexels-photo-3657575.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
        "experience": 8
    },
    {
        "name": "Chandler Hamilton",
        "gender": "Male",
        "location": "Neuville",
        "studio": "Non Company",
        "registrationDate": "2012/07/05",
        "rating": 5,
        "viewCount": 644,
        "modelCount": 188,
        "refusedCommentCount": 6,
        "acceptedCommentCount": 13,
        "description": "libero. Morbi accumsan laoreet ipsum. Curabitur consequat, lectus sit amet luctus vulputate, nisi sem semper erat, in consectetuer ipsum nunc id enim. Curabitur massa. Vestibulum accumsan neque et nunc. Quisque ornare tortor at risus. Nunc ac sem ut dolor dapibus gravida. Aliquam tincidunt,",
        "imgLink": "https://images.pexels.com/photos/3657575/pexels-photo-3657575.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
        "experience": 6
    },
    {
        "name": "Edan Rush",
        "gender": "Female",
        "location": "Virton",
        "studio": "Enim Ltd",
        "registrationDate": "2020/27/08",
        "rating": 3,
        "viewCount": 107,
        "modelCount": 92,
        "refusedCommentCount": 2,
        "acceptedCommentCount": 31,
        "description": "Maecenas ornare egestas ligula. Nullam feugiat placerat velit. Quisque varius. Nam porttitor scelerisque neque. Nullam nisl. Maecenas malesuada fringilla est. Mauris eu turpis. Nulla aliquet. Proin velit. Sed malesuada augue ut lacus. Nulla tincidunt, neque vitae",
        "imgLink": "https://i.pinimg.com/originals/11/fb/c1/11fbc17dde7df5702b71a5c1c626fcc8.jpg",
        "experience": 3
    },
    {
        "name": "Magee Blevins",
        "gender": "Male",
        "location": "Hamme",
        "studio": "Malesuada Ut Sem Corporation",
        "registrationDate": "2001/22/10",
        "rating": 4,
        "viewCount": 480,
        "modelCount": 185,
        "refusedCommentCount": 6,
        "acceptedCommentCount": 28,
        "description": "libero est, congue a, aliquet vel, vulputate eu, odio. Phasellus at augue id ante dictum cursus. Nunc mauris elit, dictum eu, eleifend nec, malesuada ut, sem. Nulla interdum. Curabitur dictum. Phasellus in felis. Nulla tempor augue ac ipsum. Phasellus vitae mauris",
        "imgLink": "https://images.pexels.com/photos/3657575/pexels-photo-3657575.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
        "experience": 6
    },
    {
        "name": "Georgia Blair",
        "gender": "Male",
        "location": "Pointe-du-Lac",
        "studio": "Lorem Semper Auctor LLP",
        "registrationDate": "2006/09/04",
        "rating": 5,
        "viewCount": 806,
        "modelCount": 92,
        "refusedCommentCount": 2,
        "acceptedCommentCount": 96,
        "description": "ornare, libero at auctor ullamcorper, nisl arcu iaculis enim, sit amet ornare lectus justo eu arcu. Morbi sit amet massa. Quisque porttitor eros nec tellus. Nunc lectus pede, ultrices a,",
        "imgLink": "https://i.pinimg.com/originals/11/fb/c1/11fbc17dde7df5702b71a5c1c626fcc8.jpg",
        "experience": 2
    },
    {
        "name": "Preston Blanchard",
        "gender": "Male",
        "location": "Alajuela",
        "studio": "Luctus Limited",
        "registrationDate": "2007/26/09",
        "rating": 1,
        "viewCount": 189,
        "modelCount": 106,
        "refusedCommentCount": 6,
        "acceptedCommentCount": 81,
        "description": "Vestibulum ut eros non enim commodo hendrerit. Donec porttitor tellus non magna. Nam ligula elit, pretium et, rutrum non, hendrerit id, ante. Nunc mauris sapien, cursus in, hendrerit consectetuer, cursus",
        "imgLink": "https://images.pexels.com/photos/3657575/pexels-photo-3657575.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
        "experience": 6
    },
    {
        "name": "Kylynn Clark",
        "gender": "Female",
        "location": "Denver",
        "studio": "Vitae Company",
        "registrationDate": "2015/27/02",
        "rating": 3,
        "viewCount": 993,
        "modelCount": 200,
        "refusedCommentCount": 10,
        "acceptedCommentCount": 83,
        "description": "egestas lacinia. Sed congue, elit sed consequat auctor, nunc nulla vulputate dui, nec tempus mauris erat eget ipsum. Suspendisse sagittis. Nullam vitae diam. Proin dolor. Nulla semper tellus id nunc",
        "imgLink": "https://i.pinimg.com/originals/11/fb/c1/11fbc17dde7df5702b71a5c1c626fcc8.jpg",
        "experience": 7
    },
    {
        "name": "Arsenio Delaney",
        "gender": "Female",
        "location": "Crecchio",
        "studio": "Scelerisque Limited",
        "registrationDate": "2008/24/12",
        "rating": 4,
        "viewCount": 325,
        "modelCount": 17,
        "refusedCommentCount": 2,
        "acceptedCommentCount": 54,
        "description": "ut odio vel est tempor bibendum. Donec felis orci, adipiscing non, luctus sit amet, faucibus ut, nulla. Cras eu tellus eu augue porttitor interdum. Sed auctor odio a purus. Duis elementum, dui quis accumsan convallis, ante lectus convallis est, vitae",
        "imgLink": "https://i.pinimg.com/originals/11/fb/c1/11fbc17dde7df5702b71a5c1c626fcc8.jpg",
        "experience": 9
    },
    {
        "name": "Riley Spencer",
        "gender": "Male",
        "location": "Villenave-d'Ornon",
        "studio": "Malesuada Fames Ac LLP",
        "registrationDate": "2003/25/11",
        "rating": 4,
        "viewCount": 811,
        "modelCount": 179,
        "refusedCommentCount": 10,
        "acceptedCommentCount": 99,
        "description": "arcu et pede. Nunc sed orci lobortis augue scelerisque mollis. Phasellus libero mauris, aliquam eu, accumsan sed, facilisis vitae, orci. Phasellus dapibus quam quis diam. Pellentesque habitant morbi tristique senectus",
        "imgLink": "https://images.pexels.com/photos/3657575/pexels-photo-3657575.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
        "experience": 1
    },
    {
        "name": "Lavinia Fernandez",
        "gender": "Female",
        "location": "St. Andrews",
        "studio": "Ut Incorporated",
        "registrationDate": "2012/17/06",
        "rating": 1,
        "viewCount": 41,
        "modelCount": 56,
        "refusedCommentCount": 5,
        "acceptedCommentCount": 36,
        "description": "felis ullamcorper viverra. Maecenas iaculis aliquet diam. Sed diam lorem, auctor quis, tristique ac, eleifend vitae, erat. Vivamus nisi. Mauris nulla. Integer urna. Vivamus molestie dapibus ligula. Aliquam erat volutpat. Nulla dignissim. Maecenas ornare egestas ligula.",
        "imgLink": "https://images.pexels.com/photos/3657575/pexels-photo-3657575.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
        "experience": 8
    },
    {
        "name": "Hakeem Maldonado",
        "gender": "Female",
        "location": "Ragnies",
        "studio": "Lorem Institute",
        "registrationDate": "2001/13/05",
        "rating": 5,
        "viewCount": 921,
        "modelCount": 101,
        "refusedCommentCount": 7,
        "acceptedCommentCount": 100,
        "description": "orci luctus et ultrices posuere cubilia Curae; Donec tincidunt. Donec vitae erat vel pede blandit congue. In scelerisque scelerisque dui. Suspendisse ac metus vitae velit egestas lacinia. Sed congue, elit sed consequat auctor, nunc nulla vulputate dui, nec tempus mauris erat eget",
        "imgLink": "https://i.pinimg.com/originals/11/fb/c1/11fbc17dde7df5702b71a5c1c626fcc8.jpg",
        "experience": 8
    },
    {
        "name": "Price Sharpe",
        "gender": "Male",
        "location": "Coltauco",
        "studio": "Metus Vivamus Inc.",
        "registrationDate": "2010/16/11",
        "rating": 3,
        "viewCount": 876,
        "modelCount": 85,
        "refusedCommentCount": 1,
        "acceptedCommentCount": 60,
        "description": "sollicitudin orci sem eget massa. Suspendisse eleifend. Cras sed leo. Cras vehicula aliquet libero. Integer in magna. Phasellus dolor elit, pellentesque a, facilisis non, bibendum sed, est. Nunc laoreet lectus quis massa. Mauris vestibulum, neque sed dictum eleifend, nunc risus varius orci, in consequat enim diam vel",
        "imgLink": "https://images.pexels.com/photos/3657575/pexels-photo-3657575.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
        "experience": 6
    },
    {
        "name": "Steel Hines",
        "gender": "Female",
        "location": "Richmond",
        "studio": "Dui Fusce Corporation",
        "registrationDate": "2001/11/03",
        "rating": 3,
        "viewCount": 387,
        "modelCount": 55,
        "refusedCommentCount": 4,
        "acceptedCommentCount": 64,
        "description": "non, cursus non, egestas a, dui. Cras pellentesque. Sed dictum. Proin eget odio. Aliquam vulputate ullamcorper magna. Sed eu eros. Nam consequat dolor vitae dolor. Donec fringilla. Donec feugiat metus sit amet ante. Vivamus non lorem vitae odio sagittis semper. Nam tempor",
        "imgLink": "https://i.pinimg.com/originals/11/fb/c1/11fbc17dde7df5702b71a5c1c626fcc8.jpg",
        "experience": 2
    },
    {
        "name": "Rae Roth",
        "gender": "Male",
        "location": "Walhain",
        "studio": "Eu Sem LLC",
        "registrationDate": "2009/16/03",
        "rating": 1,
        "viewCount": 800,
        "modelCount": 196,
        "refusedCommentCount": 7,
        "acceptedCommentCount": 20,
        "description": "luctus sit amet, faucibus ut, nulla. Cras eu tellus eu augue porttitor interdum. Sed auctor odio a purus. Duis elementum, dui quis accumsan convallis, ante lectus convallis est, vitae sodales nisi magna sed dui.",
        "imgLink": "https://images.pexels.com/photos/3657575/pexels-photo-3657575.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
        "experience": 4
    },
    {
        "name": "Ima Bass",
        "gender": "Male",
        "location": "Papasidero",
        "studio": "Ut Nisi A LLC",
        "registrationDate": "2019/26/10",
        "rating": 4,
        "viewCount": 527,
        "modelCount": 151,
        "refusedCommentCount": 3,
        "acceptedCommentCount": 69,
        "description": "facilisis eget, ipsum. Donec sollicitudin adipiscing ligula. Aenean gravida nunc sed pede. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin vel arcu eu odio tristique pharetra. Quisque ac libero nec ligula consectetuer rhoncus. Nullam",
        "imgLink": "https://images.pexels.com/photos/3657575/pexels-photo-3657575.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
        "experience": 5
    },
    {
        "name": "Driscoll Morin",
        "gender": "Male",
        "location": "Boncelles",
        "studio": "Cum Limited",
        "registrationDate": "2018/14/03",
        "rating": 5,
        "viewCount": 654,
        "modelCount": 39,
        "refusedCommentCount": 1,
        "acceptedCommentCount": 84,
        "description": "venenatis vel, faucibus id, libero. Donec consectetuer mauris id sapien. Cras dolor dolor, tempus non, lacinia at, iaculis quis, pede. Praesent eu dui. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean",
        "imgLink": "https://i.pinimg.com/originals/11/fb/c1/11fbc17dde7df5702b71a5c1c626fcc8.jpg",
        "experience": 7
    },
    {
        "name": "Daquan Marquez",
        "gender": "Male",
        "location": "La Tebaida",
        "studio": "Vivamus Molestie Incorporated",
        "registrationDate": "2012/14/06",
        "rating": 3,
        "viewCount": 777,
        "modelCount": 148,
        "refusedCommentCount": 2,
        "acceptedCommentCount": 56,
        "description": "Fusce fermentum fermentum arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus ornare. Fusce mollis. Duis sit amet diam eu dolor egestas rhoncus. Proin nisl sem, consequat nec, mollis vitae, posuere at, velit. Cras lorem lorem, luctus",
        "imgLink": "https://i.pinimg.com/originals/11/fb/c1/11fbc17dde7df5702b71a5c1c626fcc8.jpg",
        "experience": 6
    },
    {
        "name": "Colt Manning",
        "gender": "Male",
        "location": "Cumbernauld",
        "studio": "Mauris Morbi Non PC",
        "registrationDate": "2008/19/02",
        "rating": 3,
        "viewCount": 671,
        "modelCount": 65,
        "refusedCommentCount": 8,
        "acceptedCommentCount": 72,
        "description": "aliquet diam. Sed diam lorem, auctor quis, tristique ac, eleifend vitae, erat. Vivamus nisi. Mauris nulla. Integer urna. Vivamus molestie dapibus ligula. Aliquam erat volutpat. Nulla dignissim. Maecenas ornare egestas ligula. Nullam feugiat placerat velit. Quisque varius. Nam porttitor scelerisque neque.",
        "imgLink": "https://i.pinimg.com/originals/11/fb/c1/11fbc17dde7df5702b71a5c1c626fcc8.jpg",
        "experience": 1
    },
    {
        "name": "Fulton Fields",
        "gender": "Male",
        "location": "Saint-Nazaire",
        "studio": "Proin Corp.",
        "registrationDate": "2020/24/05",
        "rating": 5,
        "viewCount": 728,
        "modelCount": 148,
        "refusedCommentCount": 8,
        "acceptedCommentCount": 42,
        "description": "augue scelerisque mollis. Phasellus libero mauris, aliquam eu, accumsan sed, facilisis vitae, orci. Phasellus dapibus quam quis diam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce aliquet magna a",
        "imgLink": "https://images.pexels.com/photos/3657575/pexels-photo-3657575.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
        "experience": 4
    },
    {
        "name": "Ralph Whitehead",
        "gender": "Male",
        "location": "Laino Castello",
        "studio": "Eros Proin Ultrices Incorporated",
        "registrationDate": "2001/09/08",
        "rating": 3,
        "viewCount": 964,
        "modelCount": 139,
        "refusedCommentCount": 5,
        "acceptedCommentCount": 57,
        "description": "Curabitur ut odio vel est tempor bibendum. Donec felis orci, adipiscing non, luctus sit amet, faucibus ut, nulla. Cras eu tellus eu augue porttitor interdum. Sed auctor odio a purus. Duis elementum, dui quis accumsan convallis, ante lectus convallis est, vitae sodales nisi magna sed dui. Fusce aliquam, enim nec",
        "imgLink": "https://images.pexels.com/photos/3657575/pexels-photo-3657575.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
        "experience": 10
    },
    {
        "name": "Malik Williams",
        "gender": "Male",
        "location": "Fermont",
        "studio": "Nibh Lacinia Corporation",
        "registrationDate": "2005/02/12",
        "rating": 5,
        "viewCount": 117,
        "modelCount": 93,
        "refusedCommentCount": 4,
        "acceptedCommentCount": 66,
        "description": "sed pede nec ante blandit viverra. Donec tempus, lorem fringilla ornare placerat, orci lacus vestibulum lorem, sit amet ultricies sem magna nec quam. Curabitur vel lectus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec dignissim magna a",
        "imgLink": "https://i.pinimg.com/originals/11/fb/c1/11fbc17dde7df5702b71a5c1c626fcc8.jpg",
        "experience": 6
    },
    {
        "name": "Oleg Porter",
        "gender": "Male",
        "location": "Lewiston",
        "studio": "Massa Lobortis Foundation",
        "registrationDate": "2019/01/12",
        "rating": 4,
        "viewCount": 527,
        "modelCount": 9,
        "refusedCommentCount": 10,
        "acceptedCommentCount": 85,
        "description": "lorem, vehicula et, rutrum eu, ultrices sit amet, risus. Donec nibh enim, gravida sit amet, dapibus id, blandit at, nisi. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin vel nisl. Quisque fringilla euismod enim. Etiam gravida molestie",
        "imgLink": "https://i.pinimg.com/originals/11/fb/c1/11fbc17dde7df5702b71a5c1c626fcc8.jpg",
        "experience": 3
    },
    {
        "name": "Louis Barnett",
        "gender": "Male",
        "location": "Villers-le-Peuplier",
        "studio": "Libero Associates",
        "registrationDate": "2002/21/12",
        "rating": 1,
        "viewCount": 24,
        "modelCount": 192,
        "refusedCommentCount": 9,
        "acceptedCommentCount": 76,
        "description": "eu metus. In lorem. Donec elementum, lorem ut aliquam iaculis, lacus pede sagittis augue, eu tempor erat neque non quam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aliquam fringilla cursus purus. Nullam",
        "imgLink": "https://i.pinimg.com/originals/11/fb/c1/11fbc17dde7df5702b71a5c1c626fcc8.jpg",
        "experience": 5
    },
    {
        "name": "Akeem Koch",
        "gender": "Male",
        "location": "Bydgoszcz",
        "studio": "Vulputate Posuere Associates",
        "registrationDate": "2019/16/06",
        "rating": 4,
        "viewCount": 732,
        "modelCount": 181,
        "refusedCommentCount": 1,
        "acceptedCommentCount": 24,
        "description": "eu turpis. Nulla aliquet. Proin velit. Sed malesuada augue ut lacus. Nulla tincidunt, neque vitae semper egestas, urna justo faucibus lectus, a sollicitudin orci sem eget massa. Suspendisse eleifend. Cras sed leo.",
        "imgLink": "https://images.pexels.com/photos/3657575/pexels-photo-3657575.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
        "experience": 8
    },
    {
        "name": "Sigourney Short",
        "gender": "Female",
        "location": "Astrakhan",
        "studio": "Rutrum Eu Ultrices Foundation",
        "registrationDate": "2006/14/07",
        "rating": 5,
        "viewCount": 40,
        "modelCount": 59,
        "refusedCommentCount": 2,
        "acceptedCommentCount": 75,
        "description": "Praesent interdum ligula eu enim. Etiam imperdiet dictum magna. Ut tincidunt orci quis lectus. Nullam suscipit, est ac facilisis facilisis, magna tellus faucibus leo, in lobortis tellus justo sit amet nulla. Donec non justo. Proin non",
        "imgLink": "https://i.pinimg.com/originals/11/fb/c1/11fbc17dde7df5702b71a5c1c626fcc8.jpg",
        "experience": 6
    },
    {
        "name": "Owen Prince",
        "gender": "Female",
        "location": "Neustadt am Rübenberge",
        "studio": "Aliquam Limited",
        "registrationDate": "2018/15/03",
        "rating": 5,
        "viewCount": 632,
        "modelCount": 104,
        "refusedCommentCount": 2,
        "acceptedCommentCount": 73,
        "description": "Duis at lacus. Quisque purus sapien, gravida non, sollicitudin a, malesuada id, erat. Etiam vestibulum massa rutrum magna. Cras convallis convallis dolor. Quisque tincidunt pede ac urna. Ut tincidunt vehicula risus. Nulla",
        "imgLink": "https://i.pinimg.com/originals/11/fb/c1/11fbc17dde7df5702b71a5c1c626fcc8.jpg",
        "experience": 4
    },
    {
        "name": "Cameron Beard",
        "gender": "Female",
        "location": "Curanilahue",
        "studio": "Aliquam Eu Foundation",
        "registrationDate": "2014/01/03",
        "rating": 3,
        "viewCount": 63,
        "modelCount": 87,
        "refusedCommentCount": 8,
        "acceptedCommentCount": 10,
        "description": "erat eget ipsum. Suspendisse sagittis. Nullam vitae diam. Proin dolor. Nulla semper tellus id nunc interdum feugiat. Sed nec metus facilisis lorem tristique aliquet. Phasellus fermentum convallis ligula. Donec luctus aliquet odio. Etiam ligula tortor, dictum eu, placerat eget, venenatis a, magna. Lorem ipsum dolor sit amet,",
        "imgLink": "https://i.pinimg.com/originals/11/fb/c1/11fbc17dde7df5702b71a5c1c626fcc8.jpg",
        "experience": 5
    },
    {
        "name": "Denise Mcclure",
        "gender": "Female",
        "location": "Bakal",
        "studio": "Nostra Incorporated",
        "registrationDate": "2008/09/06",
        "rating": 1,
        "viewCount": 224,
        "modelCount": 191,
        "refusedCommentCount": 8,
        "acceptedCommentCount": 72,
        "description": "luctus felis purus ac tellus. Suspendisse sed dolor. Fusce mi lorem, vehicula et, rutrum eu, ultrices sit amet, risus. Donec nibh enim, gravida sit amet, dapibus id, blandit at, nisi. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin vel nisl.",
        "imgLink": "https://images.pexels.com/photos/3657575/pexels-photo-3657575.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
        "experience": 1
    },
    {
        "name": "Kirby Kennedy",
        "gender": "Male",
        "location": "Leoben",
        "studio": "Per Inceptos PC",
        "registrationDate": "2003/28/07",
        "rating": 5,
        "viewCount": 23,
        "modelCount": 141,
        "refusedCommentCount": 5,
        "acceptedCommentCount": 79,
        "description": "eu, euismod ac, fermentum vel, mauris. Integer sem elit, pharetra ut, pharetra sed, hendrerit a, arcu. Sed et libero. Proin mi. Aliquam gravida mauris ut mi. Duis risus odio, auctor vitae, aliquet nec, imperdiet nec, leo. Morbi neque tellus, imperdiet non, vestibulum nec, euismod in, dolor. Fusce feugiat. Lorem",
        "imgLink": "https://images.pexels.com/photos/3657575/pexels-photo-3657575.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
        "experience": 10
    },
    {
        "name": "Aristotle Adkins",
        "gender": "Male",
        "location": "Sanzeno",
        "studio": "Odio Auctor Industries",
        "registrationDate": "2013/04/12",
        "rating": 1,
        "viewCount": 722,
        "modelCount": 195,
        "refusedCommentCount": 10,
        "acceptedCommentCount": 17,
        "description": "metus vitae velit egestas lacinia. Sed congue, elit sed consequat auctor, nunc nulla vulputate dui, nec tempus mauris erat eget ipsum. Suspendisse sagittis. Nullam vitae diam. Proin dolor. Nulla semper tellus id",
        "imgLink": "https://i.pinimg.com/originals/11/fb/c1/11fbc17dde7df5702b71a5c1c626fcc8.jpg",
        "experience": 2
    },
    {
        "name": "Brock English",
        "gender": "Female",
        "location": "Enns",
        "studio": "Molestie Consulting",
        "registrationDate": "2002/07/04",
        "rating": 1,
        "viewCount": 466,
        "modelCount": 173,
        "refusedCommentCount": 6,
        "acceptedCommentCount": 87,
        "description": "amet diam eu dolor egestas rhoncus. Proin nisl sem, consequat nec, mollis vitae, posuere at, velit. Cras lorem lorem, luctus ut, pellentesque eget, dictum placerat, augue. Sed molestie. Sed id risus quis diam luctus lobortis. Class aptent",
        "imgLink": "https://i.pinimg.com/originals/11/fb/c1/11fbc17dde7df5702b71a5c1c626fcc8.jpg",
        "experience": 6
    },
    {
        "name": "Debra Bird",
        "gender": "Female",
        "location": "Saint-Denis",
        "studio": "Velit Eget Laoreet PC",
        "registrationDate": "2015/15/03",
        "rating": 3,
        "viewCount": 978,
        "modelCount": 91,
        "refusedCommentCount": 3,
        "acceptedCommentCount": 99,
        "description": "nec quam. Curabitur vel lectus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec dignissim magna a tortor. Nunc commodo auctor velit. Aliquam nisl. Nulla eu neque pellentesque massa lobortis ultrices. Vivamus rhoncus. Donec est. Nunc ullamcorper, velit in aliquet lobortis, nisi",
        "imgLink": "https://images.pexels.com/photos/3657575/pexels-photo-3657575.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
        "experience": 2
    }
]




function truncateText(selector, maxLength) {
    var element = document.querySelectorAll(selector);

    for (var i = 0; i < element.length; i++) {
        truncated = element[i].innerText;

        if (truncated.length > maxLength) {
            element[i].innerText = truncated.substr(0, maxLength) + '...';
        }
    }
}



const options = {
    valueNames: ["name", "gender", "location", "studio", "experience", "rating", "registrationDate", "viewCount", "modelCount", "refusedCommentCount", "acceptedCommentCount", "description", { name: "imgLink", attr: "src" }],
    item: "Artists",
    page: 12,
    pagination: false
}

$("#show8").click(function(event){
    if (event.target.id == '#show8') 
        console.log(event)
});



var listObj = new List("mylist",  options, data);

truncateText('div.description', 150);





/*
var theme = document.getElementById("orderby"),
paintings = document.getElementById("rev-works"),
figures = paintings.querySelectorAll("figure"),
original = paintings.innerHTML;
function sortUs(parent, child, key)
{
    var items = Array.prototype.slice.call(document.querySelectorAll(parent + " " + child)).sort(function(a, b) {
        var comparA = a.querySelector(key).innerHTML;
        var comparB = b.querySelector(key).innerHTML;
        return (comparA < comparB) ? -1 : (comparA > comparB) ? 1 : 0;
    });
    for (var i = 0; i < figures.length; i++) {
        paintings.appendChild(items[i]);
    }
}
theme.onchange = function(){
    if (theme.value == "theme")
    {
        paintings.innerHTML = original;
    }
    else
    {
        if (theme.value == "artist")
        {
            el = "span[itemprop=creator]";
        }

    if (theme.value == "date")
    {
        el = "time";
    }

    sortUs("#rev-works","figure",el);
}}*/